variable "region1_public_prefix" {}
variable "region1_private_prefix" {}
variable "region1_mgmt_prefix" {}
variable "region2_public_prefix" {}
variable "region2_private_prefix" {}
variable "region2_mgmt_prefix" {}
variable "region1_address_space" {}
variable "region2_address_space" {}
variable "region1" {}
variable "region2" {}
variable "bn_version" {}
variable "bn_build" {}
variable "vm_size" {}
variable "sipp_username" {}
variable "sipp_password" {}