variable "address_space" {}
variable "public_prefix" {}
variable "private_prefix" {}
variable "mgmt_prefix" {}
variable "resource_group" {}
variable "sipp_vm_names" {}
variable "bn_vm_names" {}
variable "location" {}
variable "bn_version" {}
variable "bn_build" {}
variable "vm_size" {}
variable "sipp_vm_size" {}
variable "sipp_username" {}
variable "sipp_password" {}